# Please list the modules first then the classes.
# Binding is useless for modules after they get included
# or a class/module uses them with extend.

methods_to_report: [
  # Modules
  'UnusedModule#unused_method',

  # Classes
  'User.last'
]
